# Generated by Django 5.2.4 on 2025-08-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_incident_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('responder', 'Responder'), ('neighborhood', 'Neighborhood'), ('admin', 'Admin')], default='neighborhood', max_length=20),
        ),
    ]
